version: '3.7'

services:
  website:
    build:
      context: .
      dockerfile: docker-images/development/Dockerfile

    restart: always
    command: lein repl :headless :host 0.0.0.0 :port 7888
    ports:
      - "7888:7888"
      - "8080:8080"

    working_dir: /app
    environment:
      - AWS_PROFILE=crux
    volumes:
      # Cache maven dependencies
      - "${HOME}/.m2:/root/.m2"
      # mount local leiningen profiles
      - "${HOME}/.lein:/root/.lein"
      # AWS credentials to upload s3 object
      - "${HOME}/.aws:/root/.aws"
      # Mount the application source and target directories
      - ./:/app
      # Run maven inside the application directory
