apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crux-standalone-webservice
  labels:
    app: crux-standalone-webservice
spec:
  serviceName: crux-standalone-webservice-service
  replicas: 1
  selector:
    matchLabels:
      app: crux-standalone-webservice
  template:
    metadata:
      labels:
        app: crux-standalone-webservice
        date: "1549290020"
    spec:
      containers:
      - name: crux-standalone-webservice
        image: juxt/crux-standalone-webservice:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/src/app/data"
          name: my-crux-volume-10
  volumeClaimTemplates:
    - metadata:
        name: my-crux-volume-10
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
               storage: 1Gi
