apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: crux-local-node-webservice
  labels:
    app: crux-local-node-webservice
spec:
  serviceName: crux-local-node-webservice-service
  replicas: 1
  selector:
    matchLabels:
      app: crux-local-node-webservice
  template:
    metadata:
      labels:
        app: crux-local-node-webservice
        date: "1549290017"
    spec:
      containers:
      - name: crux-local-node-webservice
        image: juxt/crux-standalone-webservice:latest
        env:
          - name: CRUX_MODE
            value: CLUSTER_NODE
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: "/usr/src/app/data"
          name: my-crux-volume
  volumeClaimTemplates:
    - metadata:
        name: my-crux-volume
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
               storage: 1Gi
